<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RemoteControl.Core/RemoteControl.Core.csproj" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.6.6" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
  </ItemGroup>
</Project>
